apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk2-app-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dwk2-app
  template:
    metadata:
      labels:
        app: dwk2-app
    spec:
      containers:
        - name: dwk2
          image: PROJECT/IMAGE
          ports:
            - containerPort: 3000