name: Build and publish application

on:
  push:

jobs:
  build-publish:
    name: Build, Publish, Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish backend
        run: |-
          docker build --tag "mluukkai/dwk2" .
          docker push "mluukkai/dwk2"
  